version: "2"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:10
    ports:
      - "8041:5432"
    environment:
      - POSTGRES_USER=fx
      - POSTGRES_PASSWORD=fx
      - POSTGRES_DB=fx
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - ./seeds.sql:/docker-entrypoint-initdb.d/seeds.sql