version: "2"

volumes:
  postgres-data:
    driver: local

services:
  node:
    build:
      context: .
      dockerfile:  docker/node/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ".:/var/www/"
  postgres:
    image: postgres:10
    ports:
      - "8011:5432"
    environment:
      - POSTGRES_USER=fx
      - POSTGRES_PASSWORD=fx
      - POSTGRES_DB=fx
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - ./seeds.sql:/docker-entrypoint-initdb.d/seeds.sql