version: "2"

volumes:
  postgres-data:
    driver: local

services:
  nginx:
    build:
      context: .
      dockerfile:  docker/nginx/Dockerfile
    ports:
      - "8002:80"
    volumes:
      - ".:/var/www/"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ".:/var/www/"
  postgres:
    image: postgres:10
    ports:
      - "8010:5432"
    environment:
      - POSTGRES_USER=fx
      - POSTGRES_PASSWORD=fx
      - POSTGRES_DB=fx
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - ./seeds.sql:/docker-entrypoint-initdb.d/seeds.sql